### ISSUE TITLE
Speedcontrol crashes on FFZ intergration HTTP error

### ISSUE THREAD

**Issue by j4sp3rr** [speedcontrol/nodecg-speedcontrol#4]
When the FFZ intergration meets some http error (503 in my case) from the websocket server all of speedcontrol will immidiately quit out and crash, can these errors somehow be caught and disable just FFZ intergration with a warning. possibly even try all 3 websocket addresses before giving up?
"catbag.frankerfacez.com",
"andknuckles.frankerfacez.com",
"tuturu.frankerfacez.com"
these addresses were taken from chatty code which cycles between all 3 of them.

**Comment by zoton2** [comment]
I think this issue shouldn't have happened/been fixed when you posted it, but I will close it because in testing it seems to not crash right now, and if you get an error, such as a 503, it will then attempt to reconnect (randomly to 1 of the 3 servers) after 10 seconds. Right now it won't stop ever even if it can't get a connection, but I've never seen all 3 servers refuse connections at once myself.
