### ISSUE TITLE
Custom data for players not showing on dashboard

### ISSUE THREAD

**Issue by nicnacnic** [speedcontrol/nodecg-speedcontrol#95]
I added some custom player data through the config, but the field is not showing on the dashbaord. Don't know if I have it set up wrong or that this is a bug. I'm using the latest build of the dev branch (d143be7).
```
	"customData": {
		"player": [{
			"name": "Pronouns",
			"key": "pronouns"
		}]
	}
}
```
![image](https://user-images.githubusercontent.com/39160563/105225988-63be3d80-5b2d-11eb-8f7e-128887e2f544.png)

**Comment by nicnacnic** [comment]
After much digging and testing, I managed to figure it out. Needed to use the dev branch with the commit ID `6121ef0`, and also needed to manually build the files, but now it works!
Still probably a bug that needs to be fixed, because the latest dev version removes this functionality. And more documentation on the player customData would also be a good idea, I only learned about this feature by looking the the configschema. And this is a super useful feature, I'm making a custom field for pronouns!

**Comment by zoton2** [comment]
I shall have a look into it because it *should* work on the most recent commit, although I haven't used it myself since last August or so IIRC. It's not intended to be removed (and I'll merge it into the main branch soon when I'm not so busy with other projects). Also just as a note, you'll always have to manually build files for the `dev` branch because they are not packaged with it to not clutter up the repository.

**Comment by zoton2** [comment]
OK I figured it out; turns out I messed up a PR merge and included really old main branch built files, which you were using and hence why you experienced the issue. If you use the latest commit now and build the files yourself it should be working fine, although there is not much changed between the commit you're using and the newest ones anyway (just README tweaks).
